clear

% chamadas válidas: devem continuar funcionando
class(1)
isa(1, "double")

dbstack()
dbstack(0)
dbstack("-completenames")
dbstack(0, "-completenames")

exist("sin")
exist("sin", "builtin")

which("sin")

func2str(@sin)
str2func("sin")

feval("@(x) x + 1", 4)

functions(@sin)

localfunctions()

nargin("feval")
nargout("feval")

nargin() % erro esperado fora de função/lambda
nargout() % erro esperado fora de função/lambda

narginchk(0, 2) % erro esperado fora de função/lambda
nargoutchk(0, 2) % erro esperado fora de função/lambda

eval("1 + 2")
eval("missingEvalValue", "33")

evalin("base", "1 + 2")
evalin("base", "missingEvalinValue", "44")

assignin("base", "createdByAssignin", 123)
createdByAssignin

inputname(1) % erro esperado: fora de função/lambda, mas aridade correta

% aridade inválida: todos devem lançar Invalid call to ...
class() % error: Invalid call to ...
class(1, 2) % error: Invalid call to ...

isa(1) % error: Invalid call to ...
isa(1, "double", 3) % error: Invalid call to ...

dbstack(1, "-completenames", 2) % error: Invalid call to ...

exist() % error: Invalid call to ...
exist("sin", "builtin", 3) % error: Invalid call to ...

which() % error: Invalid call to ...
which("sin", "extra") % error: Invalid call to ...

func2str() % error: Invalid call to ...
func2str(@sin, @cos) % error: Invalid call to ...

str2func() % error: Invalid call to ...
str2func("sin", "cos") % error: Invalid call to ...

feval() % error: Invalid call to ...

functions() % error: Invalid call to ...
functions(@sin, @cos) % error: Invalid call to ...

localfunctions(1) % error: Invalid call to ...

nargin(1, 2) % error: Invalid call to ...
nargout(1, 2) % error: Invalid call to ...

narginchk(0) % error: Invalid call to ...
narginchk(0, 1, 2) % error: Invalid call to ...

nargoutchk(0) % error: Invalid call to ...
nargoutchk(0, 1, 2) % error: Invalid call to ...

inputname() % error: Invalid call to ...
inputname(1, 2) % error: Invalid call to ...

eval() % error: Invalid call to ...
eval("1", "2", "3") % error: Invalid call to ...

evalin("base") % error: Invalid call to ...
evalin("base", "1", "2", "3") % error: Invalid call to ...

assignin("base", "x") % error: Invalid call to ...
assignin("base", "x", 1, 2) % error: Invalid call to ...
