clear
getconfig('precision')
configure('precision', 20)
getconfig('precision')
configure()
getconfig()
configure('crypto', true)
getconfig()
configure('real', 'number')
getconfig()
configure('real', 'decimal')
getconfig()
