version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:25.0
    steps:
      - checkout

      - run:
          name: Displays Node and npm versions
          command: |
            node -v
            npm -v

      - run:
          name: Install dependencies
          command: |
            npm install
            npm run download
            npm run build:script

      - run:
          name: Code Lint (ESLint)
          command: npm run lint

      - run:
          name: Production build (Webpack)
          command: npm run build:prod

      - run:
          name: Check output directory
          command: du -sh dist || echo "⚠️ Diretório dist não encontrado."

workflows:
  version: 2
  main_pipeline:
    jobs:
      - build
